server {
    listen 80;

    # Fallback per SPA: tutte le rotte non trovate vanno a index.html
    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
        add_header Cache-Control "public, max-age=3600";
    }
}
